"""initial_schema

Revision ID: 06ff711b82b1
Revises: 
Create Date: 2026-06-08 22:12:30.156328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ff711b82b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Text(), nullable=False),
    sa.Column('period_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mnemonic', sa.Text(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('fraction', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('placeholder', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index('idx_accounts_parent', 'accounts', ['parent_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('post_date', sa.Text(), nullable=False),
    sa.Column('enter_date', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index('idx_transactions_post_date', 'transactions', ['post_date'], unique=False)
    op.create_table('budget_amounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_num', sa.Integer(), nullable=False),
    sa.Column('amount_num', sa.Integer(), nullable=False),
    sa.Column('amount_denom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('value_num', sa.Integer(), nullable=False),
    sa.Column('value_denom', sa.Integer(), nullable=False),
    sa.Column('quantity_num', sa.Integer(), nullable=False),
    sa.Column('quantity_denom', sa.Integer(), nullable=False),
    sa.Column('reconcile_state', sa.Text(), nullable=False),
    sa.Column('reconcile_date', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index('idx_splits_account', 'splits', ['account_id'], unique=False)
    op.create_index('idx_splits_external_id', 'splits', ['external_id'], unique=True, sqlite_where=sa.text('external_id IS NOT NULL'))
    op.create_index('idx_splits_transaction', 'splits', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_splits_transaction', table_name='splits')
    op.drop_index('idx_splits_external_id', table_name='splits', sqlite_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('idx_splits_account', table_name='splits')
    op.drop_table('splits')
    op.drop_table('budget_amounts')
    op.drop_index('idx_transactions_post_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_accounts_parent', table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('commodities')
    op.drop_table('budgets')
    # ### end Alembic commands ###
